import {
  KeyRound,
  Settings,
  Users,
  UserRound,
  ShieldCheck,
  Package,
  Warehouse,
  Printer,
  ScanLine,
  FileText,
  FileSpreadsheet,
  Search,
  Filter,
  Plus,
  SquarePen,
  Trash2,
  Eye,
  Download,
  Upload,
  History,
  Bell,
  LayoutDashboard,
  CircleHelp,
  Lock,
  LogOut,
  Check,
  SearchCheck,
  ClipboardCheck
} from 'lucide-angular';

export const APP_ICONS = {
  key: KeyRound,
  settings: Settings,
  users: Users,
  user: UserRound,
  shield: ShieldCheck,
  package: Package,
  warehouse: Warehouse,
  printer: Printer,
  scan: ScanLine,
  report: FileText,
  excel: FileSpreadsheet,
  search: Search,
  filter: Filter,
  add: Plus,
  edit: SquarePen,
  delete: Trash2,
  view: Eye,
  download: Download,
  upload: Upload,
  history: History,
  bell: Bell,
  dashboard: LayoutDashboard,
  help: CircleHelp,
  lock: Lock,
  logout: LogOut,
  check: Check,
  searchCheck: SearchCheck,
  ClipboardCheck: ClipboardCheck
};

export type AppIconName = keyof typeof APP_ICONS;